-- Create reports table
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid references public.profiles(id),
  is_anonymous boolean default false,
  reason text not null,
  target text,
  description text not null,
  evidence_url text,
  status text default 'pending' check (status in ('pending', 'investigating', 'resolved', 'dismissed')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.reports enable row level security;

-- Policies for reports
create policy "Users can insert their own reports"
  on public.reports for insert
  with check (auth.uid() = reporter_id or is_anonymous = true);

create policy "Admins can view all reports"
  on public.reports for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.app_role in ('admin', 'master')
    )
  );

create policy "Admins can update reports"
  on public.reports for update
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.app_role in ('admin', 'master')
    )
  );

-- Create storage bucket for evidence
insert into storage.buckets (id, name, public)
values ('report-evidence', 'report-evidence', true)
on conflict (id) do nothing;

-- Storage policies
create policy "Authenticated users can upload evidence"
  on storage.objects for insert
  with check (
    bucket_id = 'report-evidence'
    and auth.role() = 'authenticated'
  );

create policy "Admins can view evidence"
  on storage.objects for select
  using (
    bucket_id = 'report-evidence'
    and (
        exists (
          select 1 from public.profiles
          where profiles.id = auth.uid()
          and profiles.app_role in ('admin', 'master')
        )
    )
  );
