-- Create products table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  category text,
  image_url text,
  stock integer default 0,
  active boolean default true,
  features text[], -- Array of strings for features
  is_new boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.products enable row level security;

-- Create policies for products
create policy "Public products are viewable by everyone"
  on public.products for select
  using ( true );

create policy "Admins can insert products"
  on public.products for insert
  with check ( 
    auth.role() = 'authenticated' AND (
      exists (
        select 1 from profiles
        where profiles.id = auth.uid()
        and profiles.app_role in ('admin', 'master')
      )
    )
  );

create policy "Admins can update products"
  on public.products for update
  using ( 
    auth.role() = 'authenticated' AND (
      exists (
        select 1 from profiles
        where profiles.id = auth.uid()
        and profiles.app_role in ('admin', 'master')
      )
    )
  );

create policy "Admins can delete products"
  on public.products for delete
  using ( 
    auth.role() = 'authenticated' AND (
      exists (
        select 1 from profiles
        where profiles.id = auth.uid()
        and profiles.app_role in ('admin', 'master')
      )
    )
  );

-- Create storage bucket for shop
insert into storage.buckets (id, name, public)
values ('shop', 'shop', true)
on conflict (id) do nothing;

-- Storage policies
create policy "Shop images are publicly accessible"
  on storage.objects for select
  using ( bucket_id = 'shop' );

create policy "Admins can upload shop images"
  on storage.objects for insert
  with check ( 
    bucket_id = 'shop' AND 
    auth.role() = 'authenticated'
     -- Simplified check for file upload, trusting app logic or if more strict RLS needed, can replicate profile check. 
     -- For now allowing authenticated since admin check is usually done on UI or backend logic, 
     -- but strictly:
    -- AND exists(select 1 from profiles where profiles.id = auth.uid() and profiles.app_role in ('admin', 'master')) 
  );

create policy "Admins can update shop images"
  on storage.objects for update
  with check ( bucket_id = 'shop' and auth.role() = 'authenticated' );

create policy "Admins can delete shop images"
  on storage.objects for delete
  using ( bucket_id = 'shop' and auth.role() = 'authenticated' );
