-- Create table for Likes on Admin Posts
CREATE TABLE IF NOT EXISTS public.admin_feed_likes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    post_id bigint REFERENCES public.admin_feed_posts(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, post_id)
);

-- Create table for Comments on Admin Posts
CREATE TABLE IF NOT EXISTS public.admin_feed_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    post_id bigint REFERENCES public.admin_feed_posts(id) ON DELETE CASCADE,
    text text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.admin_feed_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_feed_comments ENABLE ROW LEVEL SECURITY;

-- Policies for Likes
CREATE POLICY "Public likes are viewable by everyone" ON public.admin_feed_likes FOR SELECT USING (true);
CREATE POLICY "Users can insert their own likes" ON public.admin_feed_likes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own likes" ON public.admin_feed_likes FOR DELETE USING (auth.uid() = user_id);

-- Policies for Comments
CREATE POLICY "Public comments are viewable by everyone" ON public.admin_feed_comments FOR SELECT USING (true);
CREATE POLICY "Users can insert their own comments" ON public.admin_feed_comments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own comments" ON public.admin_feed_comments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own comments" ON public.admin_feed_comments FOR DELETE USING (auth.uid() = user_id);
