-- Create central_items table
create table if not exists public.central_items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text not null check (category in ('Aviso', 'Comunicado', 'Agenda', 'Material', 'Mensagem', 'Encontro')),
  type text check (type in ('video', 'audio', 'pdf', 'text')),
  content text,
  url text,
  date_display text,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.central_items enable row level security;

-- Create policies
create policy "Public central items are viewable by everyone"
  on public.central_items for select
  using ( active = true );

create policy "Admins can insert central items"
  on public.central_items for insert
  with check ( 
    auth.role() = 'authenticated' AND (
      exists (
        select 1 from profiles
        where profiles.id = auth.uid()
        and (profiles.app_role = 'admin' or profiles.app_role = 'master')
      )
    )
  );

create policy "Admins can update central items"
  on public.central_items for update
  using ( 
    auth.role() = 'authenticated' AND (
      exists (
        select 1 from profiles
        where profiles.id = auth.uid()
        and (profiles.app_role = 'admin' or profiles.app_role = 'master')
      )
    )
  );

create policy "Admins can delete central items"
  on public.central_items for delete
  using ( 
    auth.role() = 'authenticated' AND (
      exists (
        select 1 from profiles
        where profiles.id = auth.uid()
        and (profiles.app_role = 'admin' or profiles.app_role = 'master')
      )
    )
  );
