-- Create banners table
create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_url text,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.banners enable row level security;

-- Create policies
create policy "Public banners are viewable by everyone"
  on public.banners for select
  using ( true );

create policy "Users can insert banners"
  on public.banners for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update banners"
  on public.banners for update
  using ( auth.role() = 'authenticated' );

create policy "Users can delete banners"
  on public.banners for delete
  using ( auth.role() = 'authenticated' );

-- Create storage bucket for banners
insert into storage.buckets (id, name, public)
values ('banners', 'banners', true)
on conflict (id) do nothing;

-- Storage policies
create policy "Banner images are publicly accessible"
  on storage.objects for select
  using ( bucket_id = 'banners' );

create policy "Authenticated users can upload banner images"
  on storage.objects for insert
  with check ( bucket_id = 'banners' and auth.role() = 'authenticated' );

create policy "Authenticated users can update banner images"
  on storage.objects for update
  with check ( bucket_id = 'banners' and auth.role() = 'authenticated' );

create policy "Authenticated users can delete banner images"
  on storage.objects for delete
  using ( bucket_id = 'banners' and auth.role() = 'authenticated' );
